/* ============================================================
   Tu te mets combien ? — Données du jeu (POC)
   ------------------------------------------------------------
   Fichier .js (et non .json) pour fonctionner en ouverture
   locale (file://) sans serveur : un fetch() de .json serait
   bloqué par le navigateur (CORS).

   Pour ajouter vos propres questions : complétez le tableau
   QUESTIONS ci-dessous. Chaque entrée =
     { theme: <id d'un thème>, level: 1..10, q: '...', a: '...' }
   La difficulté doit monter du niveau 1 (facile) au 10 (dur).

   Banque de questions originale — 600 questions
   (6 thèmes × 10 niveaux × 10 questions).
   ============================================================ */

const THEMES = [
  { id: 'culture',   label: 'Culture générale', color: '#2f80ed' },
  { id: 'histgeo',   label: 'Histoire & Géo', color: '#f2994a' },
  { id: 'sciences',  label: 'Sciences & Nature', color: '#27ae60' },
  { id: 'sport',     label: 'Sport & Loisirs', color: '#eb5757' },
  { id: 'arts',      label: 'Arts & Spectacles', color: '#9b51e0' },
  { id: 'societe',   label: 'Société & Monde', color: '#00bcd4' },
];

const QUESTIONS = [
  /* ================= Culture générale ================= */
  { theme: 'culture', level:  1, q: 'De quelle couleur est le ciel par temps clair en journée ?', a: 'Bleu.' },
  { theme: 'culture', level:  1, q: 'Combien de jours compte une semaine ?', a: 'Sept.' },
  { theme: 'culture', level:  1, q: 'Quelle est la capitale de la France ?', a: 'Paris.' },
  { theme: 'culture', level:  1, q: 'Quel animal est surnommé le meilleur ami de l\'homme ?', a: 'Le chien.' },
  { theme: 'culture', level:  1, q: 'Combien de doigts compte une main humaine ?', a: 'Cinq.' },
  { theme: 'culture', level:  1, q: 'Quelle est la couleur du sang humain ?', a: 'Rouge.' },
  { theme: 'culture', level:  1, q: 'Sur quelle planète vivons-nous ?', a: 'La Terre.' },
  { theme: 'culture', level:  1, q: 'Quel fruit jaune et allongé les singes apprécient-ils ?', a: 'La banane.' },
  { theme: 'culture', level:  1, q: 'Combien de mois compte une année ?', a: 'Douze.' },
  { theme: 'culture', level:  1, q: 'Quel est le contraire du mot chaud ?', a: 'Froid.' },
  { theme: 'culture', level:  2, q: 'Quelle est la monnaie utilisée en France ?', a: 'L\'euro.' },
  { theme: 'culture', level:  2, q: 'Quel est le plus grand océan du monde ?', a: 'L\'océan Pacifique.' },
  { theme: 'culture', level:  2, q: 'Quelle est la capitale de l\'Italie ?', a: 'Rome.' },
  { theme: 'culture', level:  2, q: 'Quel est l\'animal terrestre le plus lourd ?', a: 'L\'éléphant.' },
  { theme: 'culture', level:  2, q: 'Quelle langue parle-t-on principalement en Espagne ?', a: 'L\'espagnol.' },
  { theme: 'culture', level:  2, q: 'Combien de côtés a un triangle ?', a: 'Trois.' },
  { theme: 'culture', level:  2, q: 'Quel est le premier repas de la journée ?', a: 'Le petit-déjeuner.' },
  { theme: 'culture', level:  2, q: 'Quelle planète est surnommée la planète rouge ?', a: 'Mars.' },
  { theme: 'culture', level:  2, q: 'Combien de saisons compte une année ?', a: 'Quatre.' },
  { theme: 'culture', level:  2, q: 'Comment appelle-t-on le petit de la vache ?', a: 'Le veau.' },
  { theme: 'culture', level:  3, q: 'Quel est le plus grand pays du monde par sa superficie ?', a: 'La Russie.' },
  { theme: 'culture', level:  3, q: 'Quelle est la capitale du Japon ?', a: 'Tokyo.' },
  { theme: 'culture', level:  3, q: 'Combien y a-t-il de couleurs dans un arc-en-ciel selon la tradition ?', a: 'Sept.' },
  { theme: 'culture', level:  3, q: 'Quelle est la monnaie du Royaume-Uni ?', a: 'La livre sterling.' },
  { theme: 'culture', level:  3, q: 'Quel fleuve traverse la ville de Paris ?', a: 'La Seine.' },
  { theme: 'culture', level:  3, q: 'Quelle langue est la plus parlée comme langue maternelle dans le monde ?', a: 'Le chinois mandarin.' },
  { theme: 'culture', level:  3, q: 'Dans quel pays se trouve la tour de Pise ?', a: 'En Italie.' },
  { theme: 'culture', level:  3, q: 'Quelle est la formule chimique de l\'eau ?', a: 'H2O.' },
  { theme: 'culture', level:  3, q: 'Quelle est la capitale de l\'Allemagne ?', a: 'Berlin.' },
  { theme: 'culture', level:  3, q: 'Quel oiseau blanc est le symbole de la paix ?', a: 'La colombe.' },
  { theme: 'culture', level:  4, q: 'Quelle est la capitale du Canada ?', a: 'Ottawa.' },
  { theme: 'culture', level:  4, q: 'Combien de zéros compte un million ?', a: 'Six.' },
  { theme: 'culture', level:  4, q: 'Quel est le plus grand désert chaud du monde ?', a: 'Le Sahara.' },
  { theme: 'culture', level:  4, q: 'Quelle est la monnaie du Japon ?', a: 'Le yen.' },
  { theme: 'culture', level:  4, q: 'Quel est le plus long fleuve d\'Afrique ?', a: 'Le Nil.' },
  { theme: 'culture', level:  4, q: 'Quelle expression signifie divulguer un secret par erreur ?', a: 'Vendre la mèche.' },
  { theme: 'culture', level:  4, q: 'Dans la mythologie grecque, qui est le roi des dieux ?', a: 'Zeus.' },
  { theme: 'culture', level:  4, q: 'Quelle est la capitale de l\'Australie ?', a: 'Canberra.' },
  { theme: 'culture', level:  4, q: 'Combien de cordes possède une guitare classique standard ?', a: 'Six.' },
  { theme: 'culture', level:  4, q: 'Quel métal précieux a pour symbole chimique Au ?', a: 'L\'or.' },
  { theme: 'culture', level:  5, q: 'Quelle est la capitale de l\'Égypte ?', a: 'Le Caire.' },
  { theme: 'culture', level:  5, q: 'Quel pays a pour capitale Lisbonne ?', a: 'Le Portugal.' },
  { theme: 'culture', level:  5, q: 'Que signifie l\'expression latine « carpe diem » ?', a: 'Cueille le jour (profite du moment présent).' },
  { theme: 'culture', level:  5, q: 'Quelle chaîne de montagnes sépare traditionnellement l\'Europe de l\'Asie ?', a: 'L\'Oural.' },
  { theme: 'culture', level:  5, q: 'Dans la mythologie romaine, quel dieu de la guerre correspond au grec Arès ?', a: 'Mars.' },
  { theme: 'culture', level:  5, q: 'Quelle est l\'unité de mesure de la puissance électrique ?', a: 'Le watt.' },
  { theme: 'culture', level:  5, q: 'Quel pays est surnommé le pays du Soleil-Levant ?', a: 'Le Japon.' },
  { theme: 'culture', level:  5, q: 'Quelle est la capitale de la Grèce ?', a: 'Athènes.' },
  { theme: 'culture', level:  5, q: 'Combien de lettres compte l\'alphabet français ?', a: 'Vingt-six.' },
  { theme: 'culture', level:  5, q: 'Quel est le plus petit État indépendant du monde ?', a: 'Le Vatican.' },
  { theme: 'culture', level:  6, q: 'Quelle est la capitale de la Turquie ?', a: 'Ankara.' },
  { theme: 'culture', level:  6, q: 'Quel philosophe grec fut le précepteur d\'Alexandre le Grand ?', a: 'Aristote.' },
  { theme: 'culture', level:  6, q: 'Quelle est la langue officielle du Brésil ?', a: 'Le portugais.' },
  { theme: 'culture', level:  6, q: 'Comment appelle-t-on un mot de sens contraire à un autre ?', a: 'Un antonyme.' },
  { theme: 'culture', level:  6, q: 'Quelle mer sépare l\'Europe de l\'Afrique du Nord ?', a: 'La mer Méditerranée.' },
  { theme: 'culture', level:  6, q: 'Quelle est l\'unité de mesure usuelle des angles en géométrie ?', a: 'Le degré.' },
  { theme: 'culture', level:  6, q: 'Dans la mythologie grecque, qui a dérobé le feu aux dieux pour le donner aux hommes ?', a: 'Prométhée.' },
  { theme: 'culture', level:  6, q: 'Quelle est la capitale de la Norvège ?', a: 'Oslo.' },
  { theme: 'culture', level:  6, q: 'Quel est le symbole chimique du sodium ?', a: 'Na.' },
  { theme: 'culture', level:  6, q: 'Comment appelle-t-on un mot qui se lit de la même façon dans les deux sens ?', a: 'Un palindrome.' },
  { theme: 'culture', level:  7, q: 'Quelle est la capitale de la Nouvelle-Zélande ?', a: 'Wellington.' },
  { theme: 'culture', level:  7, q: 'Quel détroit sépare l\'Espagne du Maroc ?', a: 'Le détroit de Gibraltar.' },
  { theme: 'culture', level:  7, q: 'Que signifie le préfixe « hydro- » ?', a: 'Relatif à l\'eau.' },
  { theme: 'culture', level:  7, q: 'Quelle est la monnaie de la Suisse ?', a: 'Le franc suisse.' },
  { theme: 'culture', level:  7, q: 'Dans la mythologie nordique, comment se nomme le royaume des dieux ?', a: 'Asgard.' },
  { theme: 'culture', level:  7, q: 'Quelle est la capitale du Maroc ?', a: 'Rabat.' },
  { theme: 'culture', level:  7, q: 'Comment appelle-t-on la peur des espaces clos ?', a: 'La claustrophobie.' },
  { theme: 'culture', level:  7, q: 'Quel fleuve traverse Londres ?', a: 'La Tamise.' },
  { theme: 'culture', level:  7, q: 'Quel savant italien a donné son nom à l\'unité de pression « torr » ?', a: 'Evangelista Torricelli.' },
  { theme: 'culture', level:  7, q: 'Comment appelle-t-on la science qui étudie les blasons et les armoiries ?', a: 'L\'héraldique.' },
  { theme: 'culture', level:  8, q: 'Quelle est la capitale du Kazakhstan ?', a: 'Astana.' },
  { theme: 'culture', level:  8, q: 'Que signifie l\'expression latine « alea jacta est » ?', a: 'Le sort en est jeté.' },
  { theme: 'culture', level:  8, q: 'Quel est le plus haut sommet d\'Afrique ?', a: 'Le Kilimandjaro.' },
  { theme: 'culture', level:  8, q: 'Dans la mythologie grecque, combien de travaux Hercule a-t-il accomplis ?', a: 'Douze.' },
  { theme: 'culture', level:  8, q: 'Quelle est la langue officielle de l\'Iran ?', a: 'Le persan (farsi).' },
  { theme: 'culture', level:  8, q: 'Comment appelle-t-on la figure de style qui attribue des traits humains à un objet ?', a: 'La personnification.' },
  { theme: 'culture', level:  8, q: 'Quel est le symbole chimique du potassium ?', a: 'K.' },
  { theme: 'culture', level:  8, q: 'Quelle est la capitale de la Mongolie ?', a: 'Oulan-Bator.' },
  { theme: 'culture', level:  8, q: 'Quel philosophe est l\'auteur de la formule « Je pense, donc je suis » ?', a: 'René Descartes.' },
  { theme: 'culture', level:  8, q: 'Quel est le plus grand lac d\'eau douce d\'Afrique ?', a: 'Le lac Victoria.' },
  { theme: 'culture', level:  9, q: 'Quelle est la capitale du Bhoutan ?', a: 'Thimphou.' },
  { theme: 'culture', level:  9, q: 'Que désigne le terme « oxymore » en rhétorique ?', a: 'L\'association de deux termes contradictoires.' },
  { theme: 'culture', level:  9, q: 'Quel lac salé, sans lien avec un océan, borde le point le plus bas des terres émergées ?', a: 'La mer Morte.' },
  { theme: 'culture', level:  9, q: 'Dans la mythologie grecque, quel fleuve fallait-il traverser pour rejoindre les Enfers ?', a: 'Le Styx.' },
  { theme: 'culture', level:  9, q: 'Quelle est la langue officielle principale des Philippines, aux côtés de l\'anglais ?', a: 'Le filipino (tagalog).' },
  { theme: 'culture', level:  9, q: 'Comment appelle-t-on la branche de la philosophie qui étudie la connaissance ?', a: 'L\'épistémologie.' },
  { theme: 'culture', level:  9, q: 'Quel est le symbole chimique de l\'étain ?', a: 'Sn.' },
  { theme: 'culture', level:  9, q: 'Quelle est la capitale du Suriname ?', a: 'Paramaribo.' },
  { theme: 'culture', level:  9, q: 'Comment nomme-t-on un mot emprunté tel quel à une langue étrangère ?', a: 'Un emprunt (xénisme).' },
  { theme: 'culture', level:  9, q: 'Dans quel pays se trouve la cité antique de Petra ?', a: 'En Jordanie.' },
  { theme: 'culture', level: 10, q: 'Quelle est la capitale administrative du Sri Lanka ?', a: 'Sri Jayawardenepura Kotte.' },
  { theme: 'culture', level: 10, q: 'Que désigne en linguistique le terme « hapax » ?', a: 'Un mot n\'apparaissant qu\'une seule fois dans un corpus.' },
  { theme: 'culture', level: 10, q: 'Dans la mythologie grecque, comment se nomment les trois divinités du destin ?', a: 'Les Moires (Clotho, Lachésis, Atropos).' },
  { theme: 'culture', level: 10, q: 'Quel système d\'écriture syllabique japonais est réservé notamment aux mots d\'origine étrangère ?', a: 'Le katakana.' },
  { theme: 'culture', level: 10, q: 'Comment appelle-t-on la figure de style qui désigne une chose par un de ses éléments (ex. « une voile » pour un navire) ?', a: 'La synecdoque.' },
  { theme: 'culture', level: 10, q: 'Quel est le symbole chimique de l\'antimoine ?', a: 'Sb.' },
  { theme: 'culture', level: 10, q: 'Quelle est la capitale du Kirghizistan ?', a: 'Bichkek.' },
  { theme: 'culture', level: 10, q: 'Comment nomme-t-on la peur du nombre treize ?', a: 'La triskaïdékaphobie.' },
  { theme: 'culture', level: 10, q: 'Dans la mythologie égyptienne, quel dieu à tête de chacal préside à l\'embaumement ?', a: 'Anubis.' },
  { theme: 'culture', level: 10, q: 'Quel terme grec désigne l\'étude de l\'origine et de la formation des mots ?', a: 'L\'étymologie.' },

  /* ================= Histoire & Géo ================= */
  { theme: 'histgeo', level:  1, q: 'Quelle est la capitale de la France ?', a: 'Paris.' },
  { theme: 'histgeo', level:  1, q: 'Sur quel continent se trouve l\'Égypte ?', a: 'L\'Afrique.' },
  { theme: 'histgeo', level:  1, q: 'Quel océan borde la côte ouest de la France ?', a: 'L\'océan Atlantique.' },
  { theme: 'histgeo', level:  1, q: 'Quelle est la capitale de l\'Italie ?', a: 'Rome.' },
  { theme: 'histgeo', level:  1, q: 'Quel monument parisien a été construit par Gustave Eiffel ?', a: 'La tour Eiffel.' },
  { theme: 'histgeo', level:  1, q: 'Quel pays européen a la forme d\'une botte ?', a: 'L\'Italie.' },
  { theme: 'histgeo', level:  1, q: 'Quelle est la capitale de l\'Espagne ?', a: 'Madrid.' },
  { theme: 'histgeo', level:  1, q: 'Quel fleuve traverse Paris ?', a: 'La Seine.' },
  { theme: 'histgeo', level:  1, q: 'Quelle est la capitale de l\'Allemagne ?', a: 'Berlin.' },
  { theme: 'histgeo', level:  1, q: 'Sur quel continent se trouve la France ?', a: 'L\'Europe.' },
  { theme: 'histgeo', level:  2, q: 'Quelle est la capitale du Portugal ?', a: 'Lisbonne.' },
  { theme: 'histgeo', level:  2, q: 'Quel pays est surnommé « le pays du Soleil-Levant » ?', a: 'Le Japon.' },
  { theme: 'histgeo', level:  2, q: 'En quelle année a débuté la Révolution française ?', a: '1789.' },
  { theme: 'histgeo', level:  2, q: 'Quelle est la plus haute montagne des Alpes ?', a: 'Le mont Blanc.' },
  { theme: 'histgeo', level:  2, q: 'Quel empereur français a été vaincu à la bataille de Waterloo ?', a: 'Napoléon Ier.' },
  { theme: 'histgeo', level:  2, q: 'Quelle est la capitale du Royaume-Uni ?', a: 'Londres.' },
  { theme: 'histgeo', level:  2, q: 'Quel désert couvre une grande partie du nord de l\'Afrique ?', a: 'Le Sahara.' },
  { theme: 'histgeo', level:  2, q: 'Quelle mer sépare l\'Europe de l\'Afrique du Nord ?', a: 'La mer Méditerranée.' },
  { theme: 'histgeo', level:  2, q: 'Quelle est la capitale fédérale des États-Unis ?', a: 'Washington.' },
  { theme: 'histgeo', level:  2, q: 'Quel pays a pour capitale Moscou ?', a: 'La Russie.' },
  { theme: 'histgeo', level:  3, q: 'En quelle année a eu lieu la prise de la Bastille ?', a: '1789.' },
  { theme: 'histgeo', level:  3, q: 'Quel est le plus long fleuve du monde ?', a: 'Le Nil (ou l\'Amazone selon les mesures).' },
  { theme: 'histgeo', level:  3, q: 'Quelle est la capitale de la Grèce ?', a: 'Athènes.' },
  { theme: 'histgeo', level:  3, q: 'Quel navigateur génois a atteint l\'Amérique en 1492 ?', a: 'Christophe Colomb.' },
  { theme: 'histgeo', level:  3, q: 'Quelle chaîne de montagnes sépare la France et l\'Espagne ?', a: 'Les Pyrénées.' },
  { theme: 'histgeo', level:  3, q: 'En quelle année s\'est terminée la Seconde Guerre mondiale en Europe ?', a: '1945.' },
  { theme: 'histgeo', level:  3, q: 'Quel pays possède la plus grande population du monde ?', a: 'L\'Inde.' },
  { theme: 'histgeo', level:  3, q: 'Quelle est la capitale de la Belgique ?', a: 'Bruxelles.' },
  { theme: 'histgeo', level:  3, q: 'Quel roi de France est surnommé le « Roi-Soleil » ?', a: 'Louis XIV.' },
  { theme: 'histgeo', level:  3, q: 'Quel canal relie la mer Méditerranée à la mer Rouge ?', a: 'Le canal de Suez.' },
  { theme: 'histgeo', level:  4, q: 'En quelle année a eu lieu la chute du mur de Berlin ?', a: '1989.' },
  { theme: 'histgeo', level:  4, q: 'Quelle est la capitale de l\'Australie ?', a: 'Canberra.' },
  { theme: 'histgeo', level:  4, q: 'Quel empereur romain a fait construire un célèbre mur au nord de la Grande-Bretagne ?', a: 'Hadrien.' },
  { theme: 'histgeo', level:  4, q: 'Quel est le plus grand pays du monde par sa superficie ?', a: 'La Russie.' },
  { theme: 'histgeo', level:  4, q: 'En quelle année Jules César a-t-il été assassiné ?', a: 'En 44 av. J.-C.' },
  { theme: 'histgeo', level:  4, q: 'Quel fleuve traverse Londres ?', a: 'La Tamise.' },
  { theme: 'histgeo', level:  4, q: 'Quelle est la capitale du Canada ?', a: 'Ottawa.' },
  { theme: 'histgeo', level:  4, q: 'Quel traité a mis fin à la Première Guerre mondiale en 1919 ?', a: 'Le traité de Versailles.' },
  { theme: 'histgeo', level:  4, q: 'Quelle est la plus haute montagne du monde ?', a: 'L\'Everest.' },
  { theme: 'histgeo', level:  4, q: 'Quelle reine d\'Égypte est célèbre pour ses relations avec César et Marc Antoine ?', a: 'Cléopâtre.' },
  { theme: 'histgeo', level:  5, q: 'En quelle année Christophe Colomb a-t-il atteint l\'Amérique ?', a: '1492.' },
  { theme: 'histgeo', level:  5, q: 'Quelle est la capitale de la Norvège ?', a: 'Oslo.' },
  { theme: 'histgeo', level:  5, q: 'Quel roi d\'Angleterre a fondé l\'Église anglicane au XVIe siècle ?', a: 'Henri VIII.' },
  { theme: 'histgeo', level:  5, q: 'Quel détroit sépare l\'Europe de l\'Asie à Istanbul ?', a: 'Le Bosphore.' },
  { theme: 'histgeo', level:  5, q: 'En quelle année a été signée la Déclaration d\'indépendance des États-Unis ?', a: '1776.' },
  { theme: 'histgeo', level:  5, q: 'Quel est le plus grand désert froid du monde ?', a: 'L\'Antarctique.' },
  { theme: 'histgeo', level:  5, q: 'Quelle bataille de 1815 marque la fin définitive de Napoléon ?', a: 'La bataille de Waterloo.' },
  { theme: 'histgeo', level:  5, q: 'Quelle est la capitale de la Suède ?', a: 'Stockholm.' },
  { theme: 'histgeo', level:  5, q: 'Quel empire avait pour capitale Constantinople ?', a: 'L\'Empire romain d\'Orient (byzantin).' },
  { theme: 'histgeo', level:  5, q: 'Quel est le plus haut sommet d\'Afrique ?', a: 'Le Kilimandjaro.' },
  { theme: 'histgeo', level:  6, q: 'En quelle année Jeanne d\'Arc a-t-elle été brûlée à Rouen ?', a: '1431.' },
  { theme: 'histgeo', level:  6, q: 'Quelle est la capitale de la Nouvelle-Zélande ?', a: 'Wellington.' },
  { theme: 'histgeo', level:  6, q: 'Quel traité de 1648 a mis fin à la guerre de Trente Ans ?', a: 'Les traités de Westphalie.' },
  { theme: 'histgeo', level:  6, q: 'Quel fleuve d\'Amérique du Sud a le plus grand débit du monde ?', a: 'L\'Amazone.' },
  { theme: 'histgeo', level:  6, q: 'Quel conquérant a fondé le plus vaste empire terrestre d\'un seul tenant de l\'histoire ?', a: 'Gengis Khan.' },
  { theme: 'histgeo', level:  6, q: 'Quelle est la capitale du Maroc ?', a: 'Rabat.' },
  { theme: 'histgeo', level:  6, q: 'En quelle année a eu lieu la bataille de Hastings ?', a: '1066.' },
  { theme: 'histgeo', level:  6, q: 'Quel est le lac le plus profond du monde ?', a: 'Le lac Baïkal.' },
  { theme: 'histgeo', level:  6, q: 'Quelle dynastie chinoise a bâti l\'essentiel de la Grande Muraille visible aujourd\'hui ?', a: 'La dynastie Ming.' },
  { theme: 'histgeo', level:  6, q: 'Quelle est la capitale du Kazakhstan ?', a: 'Astana.' },
  { theme: 'histgeo', level:  7, q: 'En quelle année a été signé l\'édit de Nantes par Henri IV ?', a: '1598.' },
  { theme: 'histgeo', level:  7, q: 'Quel explorateur portugais a atteint l\'Inde par la mer en contournant l\'Afrique ?', a: 'Vasco de Gama.' },
  { theme: 'histgeo', level:  7, q: 'Quelle est la capitale de la Slovénie ?', a: 'Ljubljana.' },
  { theme: 'histgeo', level:  7, q: 'Quel empire précolombien fut conquis par Francisco Pizarro ?', a: 'L\'Empire inca.' },
  { theme: 'histgeo', level:  7, q: 'Quel fleuve marque une grande partie de la frontière entre les États-Unis et le Mexique ?', a: 'Le Rio Grande.' },
  { theme: 'histgeo', level:  7, q: 'En quelle année a été promulguée la Magna Carta en Angleterre ?', a: '1215.' },
  { theme: 'histgeo', level:  7, q: 'Quelle est la capitale de l\'Arménie ?', a: 'Erevan.' },
  { theme: 'histgeo', level:  7, q: 'Quel roi des Francs a été baptisé à Reims vers 496 ?', a: 'Clovis.' },
  { theme: 'histgeo', level:  7, q: 'En quelle année Constantinople est-elle tombée aux mains des Ottomans ?', a: '1453.' },
  { theme: 'histgeo', level:  7, q: 'Quel canal d\'Amérique centrale relie l\'Atlantique au Pacifique ?', a: 'Le canal de Panama.' },
  { theme: 'histgeo', level:  8, q: 'En quelle année a eu lieu le sacre de Charlemagne comme empereur ?', a: '800.' },
  { theme: 'histgeo', level:  8, q: 'Quelle est la capitale du Bhoutan ?', a: 'Thimphou.' },
  { theme: 'histgeo', level:  8, q: 'Quel traité de 843 a partagé l\'empire de Charlemagne entre ses petits-fils ?', a: 'Le traité de Verdun.' },
  { theme: 'histgeo', level:  8, q: 'Quel pharaon a fait édifier le temple d\'Abou Simbel ?', a: 'Ramsès II.' },
  { theme: 'histgeo', level:  8, q: 'Quelle est la capitale du Kirghizistan ?', a: 'Bichkek.' },
  { theme: 'histgeo', level:  8, q: 'En quelle année a débuté la première croisade ?', a: '1096.' },
  { theme: 'histgeo', level:  8, q: 'Quel fleuve africain se jette dans le golfe de Guinée et donne son nom à un pays ?', a: 'Le Niger.' },
  { theme: 'histgeo', level:  8, q: 'Quel empereur romain a autorisé le christianisme par l\'édit de Milan en 313 ?', a: 'Constantin.' },
  { theme: 'histgeo', level:  8, q: 'Quelle est la capitale de l\'Érythrée ?', a: 'Asmara.' },
  { theme: 'histgeo', level:  8, q: 'Quelle ville italienne antique fut ensevelie par l\'éruption du Vésuve en 79 ?', a: 'Pompéi.' },
  { theme: 'histgeo', level:  9, q: 'En quelle année a eu lieu la bataille de Bouvines remportée par Philippe Auguste ?', a: '1214.' },
  { theme: 'histgeo', level:  9, q: 'Quelle est la capitale du Suriname ?', a: 'Paramaribo.' },
  { theme: 'histgeo', level:  9, q: 'Quel roi babylonien est célèbre pour son code de lois gravé au XVIIIe siècle av. J.-C. ?', a: 'Hammurabi.' },
  { theme: 'histgeo', level:  9, q: 'Quelle est la capitale du Tadjikistan ?', a: 'Douchanbé.' },
  { theme: 'histgeo', level:  9, q: 'En quelle année a été signée la paix d\'Augsbourg ?', a: '1555.' },
  { theme: 'histgeo', level:  9, q: 'Quelle bataille navale de 1571 opposa la Sainte Ligue à l\'Empire ottoman ?', a: 'La bataille de Lépante.' },
  { theme: 'histgeo', level:  9, q: 'Quelle est la capitale de la Mauritanie ?', a: 'Nouakchott.' },
  { theme: 'histgeo', level:  9, q: 'Quel empereur byzantin a fait rédiger un célèbre code de lois au VIe siècle ?', a: 'Justinien Ier.' },
  { theme: 'histgeo', level:  9, q: 'Quel général carthaginois a traversé les Alpes avec des éléphants pour attaquer Rome ?', a: 'Hannibal.' },
  { theme: 'histgeo', level:  9, q: 'Quelle est la capitale de la Géorgie (pays du Caucase) ?', a: 'Tbilissi.' },
  { theme: 'histgeo', level: 10, q: 'En quelle année a eu lieu la bataille de Poitiers remportée par Charles Martel ?', a: '732.' },
  { theme: 'histgeo', level: 10, q: 'Quelle est la capitale du Malawi ?', a: 'Lilongwe.' },
  { theme: 'histgeo', level: 10, q: 'Quel roi assyrien a constitué une célèbre bibliothèque à Ninive au VIIe siècle av. J.-C. ?', a: 'Assurbanipal.' },
  { theme: 'histgeo', level: 10, q: 'Quel traité de 1494 a partagé le Nouveau Monde entre l\'Espagne et le Portugal ?', a: 'Le traité de Tordesillas.' },
  { theme: 'histgeo', level: 10, q: 'Quel pharaon de la XVIIIe dynastie a imposé le culte du disque solaire Aton ?', a: 'Akhenaton.' },
  { theme: 'histgeo', level: 10, q: 'En quelle année s\'est déroulé le concile de Nicée convoqué par Constantin ?', a: '325.' },
  { theme: 'histgeo', level: 10, q: 'Quel est le point culminant de l\'Amérique du Nord ?', a: 'Le Denali (mont McKinley).' },
  { theme: 'histgeo', level: 10, q: 'Quelle dynastie régnait sur la Perse lors des guerres médiques contre les cités grecques ?', a: 'Les Achéménides.' },
  { theme: 'histgeo', level: 10, q: 'Quelle est la capitale du Timor oriental ?', a: 'Dili.' },
  { theme: 'histgeo', level: 10, q: 'Quelle est la capitale du Bélarus (Biélorussie) ?', a: 'Minsk.' },

  /* ================= Sciences & Nature ================= */
  { theme: 'sciences', level:  1, q: 'Combien de pattes a un chien ?', a: 'Quatre.' },
  { theme: 'sciences', level:  1, q: 'De quelle couleur est le ciel par temps clair en pleine journée ?', a: 'Bleu.' },
  { theme: 'sciences', level:  1, q: 'Quel astre nous éclaire pendant la journée ?', a: 'Le Soleil.' },
  { theme: 'sciences', level:  1, q: 'Combien de doigts compte une main humaine ?', a: 'Cinq.' },
  { theme: 'sciences', level:  1, q: 'Quel animal fait « meuh » ?', a: 'La vache.' },
  { theme: 'sciences', level:  1, q: 'En gelant, l\'eau se transforme en quoi ?', a: 'De la glace.' },
  { theme: 'sciences', level:  1, q: 'Quel organe utilise-t-on pour voir ?', a: 'Les yeux.' },
  { theme: 'sciences', level:  1, q: 'Combien de pattes possède une araignée ?', a: 'Huit.' },
  { theme: 'sciences', level:  1, q: 'De quelle couleur est généralement l\'herbe ?', a: 'Verte.' },
  { theme: 'sciences', level:  1, q: 'Quel animal est surnommé le roi des animaux ?', a: 'Le lion.' },
  { theme: 'sciences', level:  2, q: 'Quel gaz respirons-nous pour vivre ?', a: 'L\'oxygène.' },
  { theme: 'sciences', level:  2, q: 'Sur quelle planète vivons-nous ?', a: 'La Terre.' },
  { theme: 'sciences', level:  2, q: 'Quel insecte produit le miel ?', a: 'L\'abeille.' },
  { theme: 'sciences', level:  2, q: 'Combien de pattes possède un insecte ?', a: 'Six.' },
  { theme: 'sciences', level:  2, q: 'Quel est le plus grand animal terrestre actuel ?', a: 'L\'éléphant.' },
  { theme: 'sciences', level:  2, q: 'En quoi se transforme une chenille ?', a: 'Un papillon.' },
  { theme: 'sciences', level:  2, q: 'Quel liquide rouge circule dans nos vaisseaux ?', a: 'Le sang.' },
  { theme: 'sciences', level:  2, q: 'Combien de saisons compte une année ?', a: 'Quatre.' },
  { theme: 'sciences', level:  2, q: 'Quelle planète est surnommée la planète rouge ?', a: 'Mars.' },
  { theme: 'sciences', level:  2, q: 'Quel est le plus grand animal ayant jamais existé, vivant dans les océans ?', a: 'La baleine bleue.' },
  { theme: 'sciences', level:  3, q: 'Quelle est la formule chimique de l\'eau ?', a: 'H2O.' },
  { theme: 'sciences', level:  3, q: 'Quelle planète est la plus proche du Soleil ?', a: 'Mercure.' },
  { theme: 'sciences', level:  3, q: 'Combien d\'os compte environ le corps d\'un adulte ?', a: '206.' },
  { theme: 'sciences', level:  3, q: 'Quels organes permettent la respiration chez l\'humain ?', a: 'Les poumons.' },
  { theme: 'sciences', level:  3, q: 'Comment appelle-t-on un animal qui ne mange que des végétaux ?', a: 'Un herbivore.' },
  { theme: 'sciences', level:  3, q: 'Quelle étoile est la plus proche de la Terre ?', a: 'Le Soleil.' },
  { theme: 'sciences', level:  3, q: 'Quel métal courant est attiré par un aimant ?', a: 'Le fer.' },
  { theme: 'sciences', level:  3, q: 'Combien de côtés possède un carré ?', a: 'Quatre.' },
  { theme: 'sciences', level:  3, q: 'Quel est le plus grand océan du monde ?', a: 'L\'océan Pacifique.' },
  { theme: 'sciences', level:  3, q: 'Comment appelle-t-on un animal qui ne mange que de la viande ?', a: 'Un carnivore.' },
  { theme: 'sciences', level:  4, q: 'Quel gaz les plantes absorbent-elles pour la photosynthèse ?', a: 'Le dioxyde de carbone.' },
  { theme: 'sciences', level:  4, q: 'Quelle est la plus grande planète du système solaire ?', a: 'Jupiter.' },
  { theme: 'sciences', level:  4, q: 'Quel organe pompe le sang dans le corps humain ?', a: 'Le cœur.' },
  { theme: 'sciences', level:  4, q: 'Comment nomme-t-on le passage de l\'eau liquide à la vapeur ?', a: 'L\'évaporation.' },
  { theme: 'sciences', level:  4, q: 'Quel est le symbole chimique de l\'oxygène ?', a: 'O.' },
  { theme: 'sciences', level:  4, q: 'Combien de chromosomes possède une cellule humaine ?', a: '46.' },
  { theme: 'sciences', level:  4, q: 'Quel savant a énoncé la loi de la gravitation universelle ?', a: 'Isaac Newton.' },
  { theme: 'sciences', level:  4, q: 'Quel est l\'os le plus long du corps humain ?', a: 'Le fémur.' },
  { theme: 'sciences', level:  4, q: 'Comment qualifie-t-on un animal actif la nuit ?', a: 'Nocturne.' },
  { theme: 'sciences', level:  4, q: 'Quelle est la planète connue pour ses anneaux les plus spectaculaires ?', a: 'Saturne.' },
  { theme: 'sciences', level:  5, q: 'Quelle est la vitesse approximative de la lumière dans le vide ?', a: 'Environ 300 000 km/s.' },
  { theme: 'sciences', level:  5, q: 'Quel est le symbole chimique du sodium ?', a: 'Na.' },
  { theme: 'sciences', level:  5, q: 'Quel gaz est le plus abondant dans l\'atmosphère terrestre ?', a: 'L\'azote.' },
  { theme: 'sciences', level:  5, q: 'Quel organite produit l\'essentiel de l\'énergie dans la cellule ?', a: 'La mitochondrie.' },
  { theme: 'sciences', level:  5, q: 'Qui a proposé la théorie de l\'évolution par sélection naturelle ?', a: 'Charles Darwin.' },
  { theme: 'sciences', level:  5, q: 'Combien de planètes compte le système solaire ?', a: 'Huit.' },
  { theme: 'sciences', level:  5, q: 'Quel est le symbole chimique de l\'or ?', a: 'Au.' },
  { theme: 'sciences', level:  5, q: 'Quel organe de la plante réalise principalement la photosynthèse ?', a: 'La feuille.' },
  { theme: 'sciences', level:  5, q: 'Comment nomme-t-on la division cellulaire donnant deux cellules identiques ?', a: 'La mitose.' },
  { theme: 'sciences', level:  5, q: 'Quelle est la valeur du pH d\'une solution neutre à 25 °C ?', a: '7.' },
  { theme: 'sciences', level:  6, q: 'Quel est le symbole chimique du potassium ?', a: 'K.' },
  { theme: 'sciences', level:  6, q: 'Quelle est l\'unité de force du système international ?', a: 'Le newton.' },
  { theme: 'sciences', level:  6, q: 'Quel savant a découvert la pénicilline ?', a: 'Alexander Fleming.' },
  { theme: 'sciences', level:  6, q: 'Quel est le plus petit os du corps humain ?', a: 'L\'étrier.' },
  { theme: 'sciences', level:  6, q: 'Quelle particule de l\'atome porte une charge négative ?', a: 'L\'électron.' },
  { theme: 'sciences', level:  6, q: 'Quelle molécule porte l\'information génétique ?', a: 'L\'ADN.' },
  { theme: 'sciences', level:  6, q: 'Quel est le symbole chimique du fer ?', a: 'Fe.' },
  { theme: 'sciences', level:  6, q: 'Quelle planète possède les anneaux les plus visibles ?', a: 'Saturne.' },
  { theme: 'sciences', level:  6, q: 'Quelle est l\'unité de puissance du système international ?', a: 'Le watt.' },
  { theme: 'sciences', level:  6, q: 'Quel gaz noble donne une lumière rouge-orangé dans les enseignes lumineuses ?', a: 'Le néon.' },
  { theme: 'sciences', level:  7, q: 'Quel est le numéro atomique du carbone ?', a: '6.' },
  { theme: 'sciences', level:  7, q: 'Quelle théorie décrit l\'expansion de l\'univers depuis un état très dense et chaud ?', a: 'Le Big Bang.' },
  { theme: 'sciences', level:  7, q: 'Quelle est l\'unité de résistance électrique ?', a: 'L\'ohm.' },
  { theme: 'sciences', level:  7, q: 'Qui a énoncé les lois du mouvement des planètes autour du Soleil ?', a: 'Johannes Kepler.' },
  { theme: 'sciences', level:  7, q: 'Quel est le symbole chimique du mercure ?', a: 'Hg.' },
  { theme: 'sciences', level:  7, q: 'Quelle est la formule chimique du dioxyde de carbone ?', a: 'CO2.' },
  { theme: 'sciences', level:  7, q: 'Dans quelle couche de l\'atmosphère se trouve la couche d\'ozone ?', a: 'La stratosphère.' },
  { theme: 'sciences', level:  7, q: 'Quelles cellules sanguines défendent l\'organisme contre les infections ?', a: 'Les globules blancs.' },
  { theme: 'sciences', level:  7, q: 'Quelle grandeur physique vaut environ 9,81 m/s² à la surface de la Terre ?', a: 'L\'accélération de la pesanteur.' },
  { theme: 'sciences', level:  7, q: 'Quel élément a pour symbole chimique « Cu » ?', a: 'Le cuivre.' },
  { theme: 'sciences', level:  8, q: 'Quel est l\'ordre de grandeur du nombre d\'Avogadro ?', a: 'Environ 6,022 × 10²³.' },
  { theme: 'sciences', level:  8, q: 'Quelle est l\'unité du système international pour la quantité de matière ?', a: 'La mole.' },
  { theme: 'sciences', level:  8, q: 'Quel physicien a établi la relation E = mc² ?', a: 'Albert Einstein.' },
  { theme: 'sciences', level:  8, q: 'Quel est le symbole chimique du tungstène ?', a: 'W.' },
  { theme: 'sciences', level:  8, q: 'Comment nomme-t-on la désintégration spontanée d\'un noyau atomique instable ?', a: 'La radioactivité.' },
  { theme: 'sciences', level:  8, q: 'Quelle est la formule chimique du méthane ?', a: 'CH4.' },
  { theme: 'sciences', level:  8, q: 'Quel gaz, plus léger que l\'air et ininflammable, sert à gonfler les ballons ?', a: 'L\'hélium.' },
  { theme: 'sciences', level:  8, q: 'Combien de paires de chromosomes possède l\'être humain ?', a: '23.' },
  { theme: 'sciences', level:  8, q: 'Quel chimiste a conçu la première classification périodique des éléments ?', a: 'Dmitri Mendeleïev.' },
  { theme: 'sciences', level:  8, q: 'Quelle est l\'unité du système international pour la fréquence ?', a: 'Le hertz.' },
  { theme: 'sciences', level:  9, q: 'Quel est le numéro atomique de l\'or ?', a: '79.' },
  { theme: 'sciences', level:  9, q: 'Quelle particule est le médiateur de la force électromagnétique ?', a: 'Le photon.' },
  { theme: 'sciences', level:  9, q: 'Comment nomme-t-on la distance parcourue par la lumière en un an ?', a: 'L\'année-lumière.' },
  { theme: 'sciences', level:  9, q: 'Quelle enzyme sépare les deux brins de l\'ADN lors de la réplication ?', a: 'L\'hélicase.' },
  { theme: 'sciences', level:  9, q: 'Quelle est la formule chimique de l\'ammoniac ?', a: 'NH3.' },
  { theme: 'sciences', level:  9, q: 'Quel physicien a découvert le noyau atomique grâce à l\'expérience de la feuille d\'or ?', a: 'Ernest Rutherford.' },
  { theme: 'sciences', level:  9, q: 'Quel est l\'ordre de grandeur de la constante de gravitation G ?', a: 'Environ 6,67 × 10⁻¹¹ N·m²/kg².' },
  { theme: 'sciences', level:  9, q: 'Quelle réaction produit l\'énergie au cœur des étoiles ?', a: 'La fusion nucléaire.' },
  { theme: 'sciences', level:  9, q: 'Quel est le symbole chimique de l\'antimoine ?', a: 'Sb.' },
  { theme: 'sciences', level:  9, q: 'Quelle est l\'unité du système international pour la pression ?', a: 'Le pascal.' },
  { theme: 'sciences', level: 10, q: 'Quel est le numéro atomique du plutonium ?', a: '94.' },
  { theme: 'sciences', level: 10, q: 'Comment nomme-t-on la frontière d\'un trou noir au-delà de laquelle rien ne s\'échappe ?', a: 'L\'horizon des événements.' },
  { theme: 'sciences', level: 10, q: 'Quel boson, prédit par Peter Higgs, est associé à l\'origine de la masse des particules ?', a: 'Le boson de Higgs.' },
  { theme: 'sciences', level: 10, q: 'Quel est l\'ordre de grandeur de la constante de Planck ?', a: 'Environ 6,63 × 10⁻³⁴ J·s.' },
  { theme: 'sciences', level: 10, q: 'Comment nomme-t-on l\'isotope de l\'hydrogène dépourvu de neutron ?', a: 'Le protium.' },
  { theme: 'sciences', level: 10, q: 'Quel cycle de fusion de l\'hydrogène domine dans les étoiles massives ?', a: 'Le cycle CNO.' },
  { theme: 'sciences', level: 10, q: 'Quelle est l\'unité du système international pour le champ magnétique (induction) ?', a: 'Le tesla.' },
  { theme: 'sciences', level: 10, q: 'Quel physicien a énoncé le principe d\'incertitude en mécanique quantique ?', a: 'Werner Heisenberg.' },
  { theme: 'sciences', level: 10, q: 'Quelle protéine du sang transporte l\'oxygène grâce au fer qu\'elle contient ?', a: 'L\'hémoglobine.' },
  { theme: 'sciences', level: 10, q: 'Comment nomme-t-on la déviation de la lumière par un champ gravitationnel intense ?', a: 'La lentille gravitationnelle.' },

  /* ================= Sport & Loisirs ================= */
  { theme: 'sport', level:  1, q: 'Combien de joueurs compte une équipe de football sur le terrain ?', a: 'Onze.' },
  { theme: 'sport', level:  1, q: 'Dans quel sport utilise-t-on une raquette et un filet pour renvoyer une balle jaune ?', a: 'Le tennis.' },
  { theme: 'sport', level:  1, q: 'Quel sport se pratique avec un ballon orange que l\'on fait passer dans un panier ?', a: 'Le basket-ball.' },
  { theme: 'sport', level:  1, q: 'De quelle couleur est le maillot du leader du Tour de France ?', a: 'Jaune.' },
  { theme: 'sport', level:  1, q: 'Combien de temps dure un match de football réglementaire, hors prolongations ?', a: '90 minutes.' },
  { theme: 'sport', level:  1, q: 'Dans quel sport marque-t-on un but avec une rondelle sur la glace ?', a: 'Le hockey sur glace.' },
  { theme: 'sport', level:  1, q: 'Quel objet lance-t-on au bowling pour renverser les quilles ?', a: 'Une boule.' },
  { theme: 'sport', level:  1, q: 'Comment appelle-t-on la personne chargée de faire respecter les règles pendant un match de football ?', a: 'L\'arbitre.' },
  { theme: 'sport', level:  1, q: 'Dans la natation, quelle nage imite les mouvements d\'un batracien ?', a: 'La brasse.' },
  { theme: 'sport', level:  1, q: 'Combien y a-t-il d\'anneaux sur le drapeau olympique ?', a: 'Cinq.' },
  { theme: 'sport', level:  2, q: 'Tous les combien d\'années ont lieu les Jeux olympiques d\'été ?', a: 'Tous les quatre ans.' },
  { theme: 'sport', level:  2, q: 'Dans quel sport peut-on réaliser un « strike » ?', a: 'Le bowling.' },
  { theme: 'sport', level:  2, q: 'Quelle pièce du jeu d\'échecs se déplace uniquement en diagonale ?', a: 'Le fou.' },
  { theme: 'sport', level:  2, q: 'Combien de trous compte un parcours de golf classique ?', a: 'Dix-huit.' },
  { theme: 'sport', level:  2, q: 'Dans quel sport oppose-t-on deux équipes de quinze joueurs avec un ballon ovale ?', a: 'Le rugby (à XV).' },
  { theme: 'sport', level:  2, q: 'Quel terme anglais désigne un score de zéro au tennis ?', a: 'Love.' },
  { theme: 'sport', level:  2, q: 'Combien de joueurs compose une équipe de volley-ball sur le terrain ?', a: 'Six.' },
  { theme: 'sport', level:  2, q: 'Comment nomme-t-on le saut où l\'athlète franchit une barre à l\'aide d\'une longue perche ?', a: 'Le saut à la perche.' },
  { theme: 'sport', level:  2, q: 'Dans quelle ville se trouve le stade de Wembley ?', a: 'Londres.' },
  { theme: 'sport', level:  2, q: 'Combien de cartes compte chaque couleur (pique, cœur, etc.) dans un jeu de 52 cartes ?', a: 'Treize.' },
  { theme: 'sport', level:  3, q: 'Dans quel pays est né le judo ?', a: 'Le Japon.' },
  { theme: 'sport', level:  3, q: 'Dans quel sport décerne-t-on la Coupe Stanley ?', a: 'Le hockey sur glace.' },
  { theme: 'sport', level:  3, q: 'Combien de points vaut un essai au rugby à XV ?', a: 'Cinq points.' },
  { theme: 'sport', level:  3, q: 'Quelle distance parcourt-on lors d\'un marathon officiel ?', a: '42,195 km.' },
  { theme: 'sport', level:  3, q: 'Sur quel type de surface se pratiquent le judo et le karaté ?', a: 'Un tatami.' },
  { theme: 'sport', level:  3, q: 'Comment nomme-t-on la victoire dans les quatre tournois majeurs de tennis la même année ?', a: 'Le Grand Chelem.' },
  { theme: 'sport', level:  3, q: 'Dans quel pays sont nés les Jeux olympiques de l\'Antiquité ?', a: 'La Grèce.' },
  { theme: 'sport', level:  3, q: 'Combien de joueurs compte une équipe de water-polo dans l\'eau ?', a: 'Sept.' },
  { theme: 'sport', level:  3, q: 'Combien de joueurs compte une équipe de handball sur le terrain ?', a: 'Sept.' },
  { theme: 'sport', level:  3, q: 'Quelle pièce du jeu d\'échecs se déplace d\'une seule case dans toutes les directions ?', a: 'Le roi.' },
  { theme: 'sport', level:  4, q: 'En quelle année ont eu lieu les premiers Jeux olympiques modernes ?', a: 'En 1896.' },
  { theme: 'sport', level:  4, q: 'Dans quelle ville se déroulent les Internationaux de France de tennis (Roland-Garros) ?', a: 'Paris.' },
  { theme: 'sport', level:  4, q: 'Quel pays a remporté la première Coupe du monde de football, en 1930 ?', a: 'L\'Uruguay.' },
  { theme: 'sport', level:  4, q: 'Comment appelle-t-on trois strikes consécutifs au bowling ?', a: 'Un turkey (une « dinde »).' },
  { theme: 'sport', level:  4, q: 'Sur quelle surface se joue le tournoi de Wimbledon ?', a: 'Le gazon.' },
  { theme: 'sport', level:  4, q: 'Quel nageur américain détient le record de médailles d\'or olympiques ?', a: 'Michael Phelps.' },
  { theme: 'sport', level:  4, q: 'Combien de cases compte un échiquier ?', a: 'Soixante-quatre.' },
  { theme: 'sport', level:  4, q: 'Quel sport d\'hiver combine le ski de fond et le tir à la carabine ?', a: 'Le biathlon.' },
  { theme: 'sport', level:  4, q: 'De quelle couleur est le maillot du meilleur grimpeur sur le Tour de France ?', a: 'Blanc à pois rouges.' },
  { theme: 'sport', level:  4, q: 'Dans quel sport utilise-t-on un volant plutôt qu\'une balle ?', a: 'Le badminton.' },
  { theme: 'sport', level:  5, q: 'En quelle année s\'est tenue la première Coupe du monde de football ?', a: 'En 1930.' },
  { theme: 'sport', level:  5, q: 'Quelle ville espagnole a accueilli les Jeux olympiques d\'été de 1992 ?', a: 'Barcelone.' },
  { theme: 'sport', level:  5, q: 'Au basket, combien de points vaut un tir réussi au-delà de l\'arc extérieur ?', a: 'Trois points.' },
  { theme: 'sport', level:  5, q: 'Comment nomme-t-on le grand tour cycliste par étapes disputé en Italie ?', a: 'Le Giro (Tour d\'Italie).' },
  { theme: 'sport', level:  5, q: 'Combien de temps dure une période au hockey sur glace ?', a: 'Vingt minutes.' },
  { theme: 'sport', level:  5, q: 'Quel footballeur argentin est surnommé « la Pulga » (la Puce) ?', a: 'Lionel Messi.' },
  { theme: 'sport', level:  5, q: 'Quel sport de combat Mohamed Ali a-t-il pratiqué ?', a: 'La boxe.' },
  { theme: 'sport', level:  5, q: 'Dans quel pays le cricket a-t-il été inventé ?', a: 'L\'Angleterre.' },
  { theme: 'sport', level:  5, q: 'Quelle pièce du jeu d\'échecs peut sauter par-dessus les autres pièces ?', a: 'Le cavalier.' },
  { theme: 'sport', level:  5, q: 'Quel sprinteur jamaïcain détient les records du monde du 100 m et du 200 m ?', a: 'Usain Bolt.' },
  { theme: 'sport', level:  6, q: 'Quelle classique cycliste belge du printemps est surnommée « la Doyenne » ?', a: 'Liège-Bastogne-Liège.' },
  { theme: 'sport', level:  6, q: 'En quelle année la France a-t-elle remporté sa première Coupe du monde de football ?', a: 'En 1998.' },
  { theme: 'sport', level:  6, q: 'Quel pilote allemand a remporté sept titres de champion du monde de Formule 1 ?', a: 'Michael Schumacher.' },
  { theme: 'sport', level:  6, q: 'Dans quel jeu existe la prise « en passant » ?', a: 'Aux échecs.' },
  { theme: 'sport', level:  6, q: 'Quel tournoi du Grand Chelem de tennis se dispute au mois de janvier ?', a: 'L\'Open d\'Australie.' },
  { theme: 'sport', level:  6, q: 'Combien de joueurs compte une équipe de rugby à XIII sur le terrain ?', a: 'Treize.' },
  { theme: 'sport', level:  6, q: 'Quel boxeur américain était surnommé « The Greatest » ?', a: 'Muhammad Ali.' },
  { theme: 'sport', level:  6, q: 'Dans quelle discipline de l\'athlétisme lance-t-on un boulet relié à un câble en tournant sur soi-même ?', a: 'Le lancer du marteau.' },
  { theme: 'sport', level:  6, q: 'Quel pays a organisé et remporté la Coupe du monde de football de 1966 ?', a: 'L\'Angleterre.' },
  { theme: 'sport', level:  6, q: 'Quel trophée est remis au vainqueur du Super Bowl de football américain ?', a: 'Le trophée Vince Lombardi.' },
  { theme: 'sport', level:  7, q: 'En quelle année Roger Bannister a-t-il couru le mile en moins de quatre minutes pour la première fois ?', a: 'En 1954.' },
  { theme: 'sport', level:  7, q: 'Quel cycliste belge, surnommé « le Cannibale », a remporté cinq Tours de France ?', a: 'Eddy Merckx.' },
  { theme: 'sport', level:  7, q: 'Comment appelle-t-on l\'ouverture d\'échecs 1.e4 e5 2.Cf3 Cc6 3.Fb5 ?', a: 'La partie espagnole (Ruy Lopez).' },
  { theme: 'sport', level:  7, q: 'Quelle ville française a accueilli les premiers Jeux olympiques d\'hiver, en 1924 ?', a: 'Chamonix.' },
  { theme: 'sport', level:  7, q: 'Quel joueur de tennis suédois a remporté cinq fois Wimbledon de suite de 1976 à 1980 ?', a: 'Björn Borg.' },
  { theme: 'sport', level:  7, q: 'Dans quel sport décerne-t-on le « Ballon d\'Or » depuis 1956 ?', a: 'Le football.' },
  { theme: 'sport', level:  7, q: 'Combien de nations participent aujourd\'hui au Tournoi de rugby européen ?', a: 'Six (le Tournoi des Six Nations).' },
  { theme: 'sport', level:  7, q: 'Combien de pièces chaque joueur possède-t-il au début d\'une partie d\'échecs ?', a: 'Seize.' },
  { theme: 'sport', level:  7, q: 'Quelle gymnaste roumaine a obtenu le premier 10 parfait des Jeux olympiques, en 1976 ?', a: 'Nadia Comaneci.' },
  { theme: 'sport', level:  7, q: 'Comment se nomme la course automobile d\'endurance disputée sur 24 heures en France ?', a: 'Les 24 Heures du Mans.' },
  { theme: 'sport', level:  8, q: 'Qui fut le premier champion du monde d\'échecs officiellement reconnu, en 1886 ?', a: 'Wilhelm Steinitz.' },
  { theme: 'sport', level:  8, q: 'Quelle arme d\'escrime autorise les touches avec la pointe comme avec le tranchant ?', a: 'Le sabre.' },
  { theme: 'sport', level:  8, q: 'En quelle année les femmes ont-elles participé pour la première fois aux Jeux olympiques modernes ?', a: 'En 1900.' },
  { theme: 'sport', level:  8, q: 'Quel joueur a inscrit le « but du siècle » lors de la Coupe du monde 1986 contre l\'Angleterre ?', a: 'Diego Maradona.' },
  { theme: 'sport', level:  8, q: 'Aux échecs, comment nomme-t-on la position où un joueur ne peut plus jouer sans mettre son roi en échec, sans y être ?', a: 'Le pat.' },
  { theme: 'sport', level:  8, q: 'Quel cheval de course a remporté la Triple Couronne américaine en 1973 avec des records toujours invaincus ?', a: 'Secretariat.' },
  { theme: 'sport', level:  8, q: 'Quelle nation a remporté la toute première Coupe Davis de tennis, en 1900 ?', a: 'Les États-Unis.' },
  { theme: 'sport', level:  8, q: 'Quel athlète américain a remporté quatre médailles d\'or aux Jeux olympiques de Berlin en 1936 ?', a: 'Jesse Owens.' },
  { theme: 'sport', level:  8, q: 'Quel jeu de plateau d\'origine asiatique se joue avec des pierres noires et blanches sur un quadrillage ?', a: 'Le go.' },
  { theme: 'sport', level:  8, q: 'Quel coureur finlandais, surnommé « le Finlandais volant », a remporté neuf titres olympiques dans les années 1920 ?', a: 'Paavo Nurmi.' },
  { theme: 'sport', level:  9, q: 'Quel champion soviétique Bobby Fischer a-t-il battu en 1972 à Reykjavik pour le titre mondial d\'échecs ?', a: 'Boris Spassky.' },
  { theme: 'sport', level:  9, q: 'Quel joueur de cricket australien détient une moyenne à la batte de 99,94, réputée insurpassable ?', a: 'Donald Bradman.' },
  { theme: 'sport', level:  9, q: 'En quelle année a été disputée la première édition de Paris-Roubaix ?', a: 'En 1896.' },
  { theme: 'sport', level:  9, q: 'Quelle est la longueur réglementaire d\'une piste d\'escrime ?', a: 'Quatorze mètres.' },
  { theme: 'sport', level:  9, q: 'Quel joueur de tennis australien a réalisé le Grand Chelem calendaire en 1962 puis en 1969 ?', a: 'Rod Laver.' },
  { theme: 'sport', level:  9, q: 'Aux échecs, quel mat rapide, visant la case f7, doit son nom à un métier ?', a: 'Le mat du berger.' },
  { theme: 'sport', level:  9, q: 'Quel pilote argentin a remporté cinq titres mondiaux de Formule 1 dans les années 1950 ?', a: 'Juan Manuel Fangio.' },
  { theme: 'sport', level:  9, q: 'Quelle est la hauteur réglementaire d\'un panier de basket-ball ?', a: '3,05 mètres.' },
  { theme: 'sport', level:  9, q: 'Quel rameur britannique a remporté cinq médailles d\'or lors de cinq olympiades consécutives ?', a: 'Steve Redgrave.' },
  { theme: 'sport', level:  9, q: 'En quelle année la FIDE a-t-elle organisé le championnat du monde d\'échecs après la mort d\'Alekhine ?', a: 'En 1948.' },
  { theme: 'sport', level: 10, q: 'Contre quelle équipe la France a-t-elle disputé son premier match en Coupe du monde 1930 ?', a: 'Le Mexique.' },
  { theme: 'sport', level: 10, q: 'Quel théoricien des échecs, figure de l\'école hypermoderne, est l\'auteur de « Mon système » ?', a: 'Aaron Nimzowitsch.' },
  { theme: 'sport', level: 10, q: 'Quel athlète américain a détenu le record du saut en longueur pendant vingt-trois ans après son bond de 8,90 m à Mexico en 1968 ?', a: 'Bob Beamon.' },
  { theme: 'sport', level: 10, q: 'Quel coureur italien fut le premier à réaliser le doublé Giro-Tour la même année, en 1949 ?', a: 'Fausto Coppi.' },
  { theme: 'sport', level: 10, q: 'Comment se nomme la défense d\'échecs caractérisée par les coups 1.e4 c5 ?', a: 'La défense sicilienne.' },
  { theme: 'sport', level: 10, q: 'Quel escrimeur hongrois a remporté six médailles d\'or olympiques au sabre entre 1932 et 1960 ?', a: 'Aladar Gerevich.' },
  { theme: 'sport', level: 10, q: 'En quelle année eut lieu le premier match international de football, entre l\'Écosse et l\'Angleterre ?', a: 'En 1872.' },
  { theme: 'sport', level: 10, q: 'Quel joueur de tennis français des « Mousquetaires » était surnommé « le Basque bondissant » ?', a: 'Jean Borotra.' },
  { theme: 'sport', level: 10, q: 'De quelle nage la nage papillon s\'est-elle détachée pour devenir une discipline olympique distincte ?', a: 'La brasse.' },
  { theme: 'sport', level: 10, q: 'Quelle course hippique anglaise, créée en 1776, est la plus ancienne des cinq « classiques » de plat ?', a: 'Le St. Leger.' },

  /* ================= Arts & Spectacles ================= */
  { theme: 'arts', level:  1, q: 'Qui a peint « La Joconde » ?', a: 'Léonard de Vinci.' },
  { theme: 'arts', level:  1, q: 'Quel célèbre personnage de Walt Disney est une souris ?', a: 'Mickey Mouse.' },
  { theme: 'arts', level:  1, q: 'Quel instrument de musique possède des touches blanches et noires et se joue assis ?', a: 'Le piano.' },
  { theme: 'arts', level:  1, q: 'Dans quelle ville se trouve la tour Eiffel ?', a: 'Paris.' },
  { theme: 'arts', level:  1, q: 'Qui a écrit la série de romans « Harry Potter » ?', a: 'J.K. Rowling.' },
  { theme: 'arts', level:  1, q: 'Quelle danse classique se pratique notamment sur des pointes ?', a: 'Le ballet.' },
  { theme: 'arts', level:  1, q: 'Quel héros de bande dessinée belge a pour compagnon un chien blanc nommé Milou ?', a: 'Tintin.' },
  { theme: 'arts', level:  1, q: 'Combien de cordes possède une guitare classique standard ?', a: 'Six.' },
  { theme: 'arts', level:  1, q: 'Quel grand musée parisien abrite « La Joconde » ?', a: 'Le Louvre.' },
  { theme: 'arts', level:  1, q: 'Quel film d\'animation de Disney raconte l\'histoire d\'un jeune lion nommé Simba ?', a: 'Le Roi lion.' },
  { theme: 'arts', level:  2, q: 'Qui a peint « La Nuit étoilée » ?', a: 'Vincent van Gogh.' },
  { theme: 'arts', level:  2, q: 'Quel compositeur allemand a écrit la célèbre pièce pour piano « La Lettre à Élise » ?', a: 'Ludwig van Beethoven.' },
  { theme: 'arts', level:  2, q: 'Qui a réalisé le film « Titanic » (1997) ?', a: 'James Cameron.' },
  { theme: 'arts', level:  2, q: 'Quel écrivain français a écrit « Le Petit Prince » ?', a: 'Antoine de Saint-Exupéry.' },
  { theme: 'arts', level:  2, q: 'Quelle statue offerte par la France se dresse à l\'entrée du port de New York ?', a: 'La statue de la Liberté.' },
  { theme: 'arts', level:  2, q: 'Quel peintre espagnol est l\'un des fondateurs du cubisme ?', a: 'Pablo Picasso.' },
  { theme: 'arts', level:  2, q: 'Quel dramaturge anglais a écrit « Roméo et Juliette » ?', a: 'William Shakespeare.' },
  { theme: 'arts', level:  2, q: 'Quel groupe britannique comptait John Lennon et Paul McCartney ?', a: 'Les Beatles.' },
  { theme: 'arts', level:  2, q: 'Qui a sculpté « Le Penseur » ?', a: 'Auguste Rodin.' },
  { theme: 'arts', level:  2, q: 'Quel peintre néerlandais s\'est coupé une partie de l\'oreille ?', a: 'Vincent van Gogh.' },
  { theme: 'arts', level:  3, q: 'Qui a peint le plafond de la chapelle Sixtine ?', a: 'Michel-Ange.' },
  { theme: 'arts', level:  3, q: 'Quel compositeur autrichien, enfant prodige, a composé l\'opéra « La Flûte enchantée » ?', a: 'Wolfgang Amadeus Mozart.' },
  { theme: 'arts', level:  3, q: 'Qui a écrit le roman « Les Misérables » ?', a: 'Victor Hugo.' },
  { theme: 'arts', level:  3, q: 'Quel réalisateur américain a créé la saga « Star Wars » ?', a: 'George Lucas.' },
  { theme: 'arts', level:  3, q: 'Quel peintre a donné son nom à l\'impressionnisme avec « Impression, soleil levant » ?', a: 'Claude Monet.' },
  { theme: 'arts', level:  3, q: 'Quel ingénieur a conçu la tour construite pour l\'Exposition universelle de 1889 à Paris ?', a: 'Gustave Eiffel.' },
  { theme: 'arts', level:  3, q: 'Quel écrivain français a écrit « Madame Bovary » ?', a: 'Gustave Flaubert.' },
  { theme: 'arts', level:  3, q: 'Quelle célèbre salle d\'opéra se trouve à Milan ?', a: 'La Scala.' },
  { theme: 'arts', level:  3, q: 'Qui a écrit les scénarios des premières aventures d\'Astérix ?', a: 'René Goscinny.' },
  { theme: 'arts', level:  3, q: 'Quel compositeur italien a écrit l\'opéra « Le Barbier de Séville » ?', a: 'Gioachino Rossini.' },
  { theme: 'arts', level:  4, q: 'Qui a peint « Guernica » ?', a: 'Pablo Picasso.' },
  { theme: 'arts', level:  4, q: 'Quel compositeur russe a composé le ballet « Le Lac des cygnes » ?', a: 'Piotr Ilitch Tchaïkovski.' },
  { theme: 'arts', level:  4, q: 'Qui a écrit le roman « Cent ans de solitude » ?', a: 'Gabriel García Márquez.' },
  { theme: 'arts', level:  4, q: 'Quel réalisateur italien a réalisé « La Dolce Vita » ?', a: 'Federico Fellini.' },
  { theme: 'arts', level:  4, q: 'Quel peintre néerlandais du XVIIe siècle a peint « La Ronde de nuit » ?', a: 'Rembrandt.' },
  { theme: 'arts', level:  4, q: 'Quel architecte espagnol a conçu la basilique de la Sagrada Família à Barcelone ?', a: 'Antoni Gaudí.' },
  { theme: 'arts', level:  4, q: 'Quel écrivain russe a écrit « Guerre et Paix » ?', a: 'Léon Tolstoï.' },
  { theme: 'arts', level:  4, q: 'Quel style musical est né à La Nouvelle-Orléans au début du XXe siècle ?', a: 'Le jazz.' },
  { theme: 'arts', level:  4, q: 'Quel sculpteur a réalisé le « David » en marbre conservé à Florence ?', a: 'Michel-Ange.' },
  { theme: 'arts', level:  4, q: 'Quel dessinateur belge a créé le personnage de Gaston Lagaffe ?', a: 'André Franquin.' },
  { theme: 'arts', level:  5, q: 'Qui a peint « Le Cri » ?', a: 'Edvard Munch.' },
  { theme: 'arts', level:  5, q: 'Quel compositeur français a écrit l\'opéra « Carmen » ?', a: 'Georges Bizet.' },
  { theme: 'arts', level:  5, q: 'Qui a écrit le roman « Crime et Châtiment » ?', a: 'Fiodor Dostoïevski.' },
  { theme: 'arts', level:  5, q: 'Quel réalisateur britannique a réalisé le film « Psychose » ?', a: 'Alfred Hitchcock.' },
  { theme: 'arts', level:  5, q: 'Quel artiste espagnol a peint « La Persistance de la mémoire », célèbre pour ses montres molles ?', a: 'Salvador Dalí.' },
  { theme: 'arts', level:  5, q: 'Quel mouvement pictural du début du XXe siècle est associé à Matisse et aux couleurs vives ?', a: 'Le fauvisme.' },
  { theme: 'arts', level:  5, q: 'Quelle romancière britannique a créé le détective Hercule Poirot ?', a: 'Agatha Christie.' },
  { theme: 'arts', level:  5, q: 'Quel compositeur baroque allemand a écrit les « Variations Goldberg » ?', a: 'Jean-Sébastien Bach.' },
  { theme: 'arts', level:  5, q: 'Quel luthier italien de Crémone est le plus célèbre fabricant de violons ?', a: 'Antonio Stradivari.' },
  { theme: 'arts', level:  5, q: 'Quel peintre autrichien a peint « Le Baiser », œuvre recouverte de feuilles d\'or ?', a: 'Gustav Klimt.' },
  { theme: 'arts', level:  6, q: 'Quel peintre a réalisé « Le Déjeuner sur l\'herbe » (1863) ?', a: 'Édouard Manet.' },
  { theme: 'arts', level:  6, q: 'Quel compositeur allemand a écrit « La Chevauchée des Walkyries » ?', a: 'Richard Wagner.' },
  { theme: 'arts', level:  6, q: 'Qui a écrit « À la recherche du temps perdu » ?', a: 'Marcel Proust.' },
  { theme: 'arts', level:  6, q: 'Quel réalisateur japonais a réalisé « Les Sept Samouraïs » ?', a: 'Akira Kurosawa.' },
  { theme: 'arts', level:  6, q: 'Quel peintre néerlandais a peint « La Jeune Fille à la perle » ?', a: 'Johannes Vermeer.' },
  { theme: 'arts', level:  6, q: 'Quel architecte franco-suisse a conçu la Villa Savoye à Poissy ?', a: 'Le Corbusier.' },
  { theme: 'arts', level:  6, q: 'Quel poète français a écrit le recueil « Les Fleurs du mal » ?', a: 'Charles Baudelaire.' },
  { theme: 'arts', level:  6, q: 'Quel compositeur français a écrit le « Boléro » ?', a: 'Maurice Ravel.' },
  { theme: 'arts', level:  6, q: 'Quelle danseuse américaine fut une pionnière de la danse moderne au début du XXe siècle ?', a: 'Isadora Duncan.' },
  { theme: 'arts', level:  6, q: 'Quel dessinateur américain a créé la bande dessinée « Peanuts » et le chien Snoopy ?', a: 'Charles M. Schulz.' },
  { theme: 'arts', level:  7, q: 'Qui a peint « American Gothic » ?', a: 'Grant Wood.' },
  { theme: 'arts', level:  7, q: 'Quel compositeur russe a écrit le ballet « Le Sacre du printemps » ?', a: 'Igor Stravinsky.' },
  { theme: 'arts', level:  7, q: 'Qui a écrit le roman « L\'Étranger » ?', a: 'Albert Camus.' },
  { theme: 'arts', level:  7, q: 'Quel réalisateur suédois a réalisé « Le Septième Sceau » ?', a: 'Ingmar Bergman.' },
  { theme: 'arts', level:  7, q: 'Quel peintre a fondé le mouvement De Stijl avec ses compositions de rectangles colorés ?', a: 'Piet Mondrian.' },
  { theme: 'arts', level:  7, q: 'Quel architecte américain a conçu la maison sur la cascade (Fallingwater) ?', a: 'Frank Lloyd Wright.' },
  { theme: 'arts', level:  7, q: 'Quel écrivain irlandais a écrit le roman « Ulysse » ?', a: 'James Joyce.' },
  { theme: 'arts', level:  7, q: 'Quel compositeur italien a écrit l\'opéra « La Traviata » ?', a: 'Giuseppe Verdi.' },
  { theme: 'arts', level:  7, q: 'Quel danseur des Ballets russes a chorégraphié la création du « Sacre du printemps » en 1913 ?', a: 'Vaslav Nijinski.' },
  { theme: 'arts', level:  7, q: 'Quel peintre français a réalisé de nombreuses scènes de danseuses, dont « La Classe de danse » ?', a: 'Edgar Degas.' },
  { theme: 'arts', level:  8, q: 'Qui a peint le triptyque « Le Jardin des délices » ?', a: 'Jérôme Bosch.' },
  { theme: 'arts', level:  8, q: 'Quel compositeur norvégien a écrit la musique de scène de « Peer Gynt » ?', a: 'Edvard Grieg.' },
  { theme: 'arts', level:  8, q: 'Qui a écrit le roman « Le Bruit et la Fureur » ?', a: 'William Faulkner.' },
  { theme: 'arts', level:  8, q: 'Quel réalisateur soviétique a réalisé « Le Cuirassé Potemkine » ?', a: 'Sergueï Eisenstein.' },
  { theme: 'arts', level:  8, q: 'Quel peintre italien de la Renaissance a peint « La Naissance de Vénus » ?', a: 'Sandro Botticelli.' },
  { theme: 'arts', level:  8, q: 'Quel architecte a conçu le musée Guggenheim de Bilbao ?', a: 'Frank Gehry.' },
  { theme: 'arts', level:  8, q: 'Quel poète italien a écrit « La Divine Comédie » ?', a: 'Dante Alighieri.' },
  { theme: 'arts', level:  8, q: 'Quel compositeur hongrois a écrit les « Rhapsodies hongroises » pour piano ?', a: 'Franz Liszt.' },
  { theme: 'arts', level:  8, q: 'Quel sculpteur roumain a créé la série « L\'Oiseau dans l\'espace » ?', a: 'Constantin Brancusi.' },
  { theme: 'arts', level:  8, q: 'Quel dramaturge norvégien a écrit la pièce « Une maison de poupée » ?', a: 'Henrik Ibsen.' },
  { theme: 'arts', level:  9, q: 'Qui a peint « Les Ménines » ?', a: 'Diego Vélasquez.' },
  { theme: 'arts', level:  9, q: 'Quel compositeur français a écrit l\'opéra « Pelléas et Mélisande » ?', a: 'Claude Debussy.' },
  { theme: 'arts', level:  9, q: 'Qui a écrit le roman « La Montagne magique » ?', a: 'Thomas Mann.' },
  { theme: 'arts', level:  9, q: 'Quel réalisateur danois a réalisé « La Passion de Jeanne d\'Arc » (1928) ?', a: 'Carl Theodor Dreyer.' },
  { theme: 'arts', level:  9, q: 'Quel artiste allemand de la Renaissance a réalisé la gravure « Melencolia I » ?', a: 'Albrecht Dürer.' },
  { theme: 'arts', level:  9, q: 'Quel architecte a conçu le pavillon allemand de l\'Exposition de Barcelone de 1929 ?', a: 'Ludwig Mies van der Rohe.' },
  { theme: 'arts', level:  9, q: 'Quel écrivain autrichien a écrit le roman inachevé « L\'Homme sans qualités » ?', a: 'Robert Musil.' },
  { theme: 'arts', level:  9, q: 'Quel compositeur autrichien est à l\'origine du dodécaphonisme (musique à douze sons) ?', a: 'Arnold Schoenberg.' },
  { theme: 'arts', level:  9, q: 'Quel chorégraphe d\'origine russe a cofondé le New York City Ballet ?', a: 'George Balanchine.' },
  { theme: 'arts', level:  9, q: 'Quel peintre allemand a réalisé le retable d\'Issenheim ?', a: 'Matthias Grünewald.' },
  { theme: 'arts', level: 10, q: 'Quel peintre flamand a achevé le « Polyptyque de l\'Agneau mystique » à Gand ?', a: 'Jan van Eyck.' },
  { theme: 'arts', level: 10, q: 'Quel compositeur autrichien a écrit l\'opéra « Wozzeck » ?', a: 'Alban Berg.' },
  { theme: 'arts', level: 10, q: 'Quel écrivain américain a écrit le roman « L\'Arc-en-ciel de la gravité » ?', a: 'Thomas Pynchon.' },
  { theme: 'arts', level: 10, q: 'Quel réalisateur soviétique a réalisé le film « Andreï Roublev » ?', a: 'Andreï Tarkovski.' },
  { theme: 'arts', level: 10, q: 'Quel peintre siennois du XIVe siècle a réalisé la « Maestà » de la cathédrale de Sienne ?', a: 'Duccio di Buoninsegna.' },
  { theme: 'arts', level: 10, q: 'Quel architecte baroque italien a conçu l\'église Saint-Charles-aux-Quatre-Fontaines à Rome ?', a: 'Francesco Borromini.' },
  { theme: 'arts', level: 10, q: 'Quel poète romain de l\'Antiquité a écrit « Les Métamorphoses » ?', a: 'Ovide.' },
  { theme: 'arts', level: 10, q: 'Quel compositeur russe a laissé inachevé l\'opéra « La Khovantchina » ?', a: 'Modeste Moussorgski.' },
  { theme: 'arts', level: 10, q: 'Quel peintre a écrit le traité théorique « Du spirituel dans l\'art » (1911) ?', a: 'Vassily Kandinsky.' },
  { theme: 'arts', level: 10, q: 'Quel sculpteur florentin du Quattrocento a réalisé un « David » en bronze, antérieur à celui de Michel-Ange ?', a: 'Donatello.' },

  /* ================= Société & Monde ================= */
  { theme: 'societe', level:  1, q: 'Quelle est la capitale de la France ?', a: 'Paris.' },
  { theme: 'societe', level:  1, q: 'Quelles sont les trois couleurs du drapeau français ?', a: 'Bleu, blanc, rouge.' },
  { theme: 'societe', level:  1, q: 'Quelle monnaie utilise-t-on en France ?', a: 'L\'euro.' },
  { theme: 'societe', level:  1, q: 'Sur quel continent se trouve la France ?', a: 'L\'Europe.' },
  { theme: 'societe', level:  1, q: 'Quel animal est un symbole de la France ?', a: 'Le coq.' },
  { theme: 'societe', level:  1, q: 'Quel numéro compose-t-on pour les urgences dans toute l\'Europe ?', a: 'Le 112.' },
  { theme: 'societe', level:  1, q: 'Quel jour est célébrée la fête nationale française ?', a: 'Le 14 juillet.' },
  { theme: 'societe', level:  1, q: 'Quelle est la langue officielle de la France ?', a: 'Le français.' },
  { theme: 'societe', level:  1, q: 'Dans quelle ville se trouve la tour Eiffel ?', a: 'Paris.' },
  { theme: 'societe', level:  1, q: 'Que signifie le sigle UE ?', a: 'Union européenne.' },
  { theme: 'societe', level:  2, q: 'Quelle est la devise de la République française ?', a: 'Liberté, Égalité, Fraternité.' },
  { theme: 'societe', level:  2, q: 'Dans quel palais réside le président de la République française ?', a: 'Le palais de l\'Élysée.' },
  { theme: 'societe', level:  2, q: 'Quel est le continent le plus peuplé du monde ?', a: 'L\'Asie.' },
  { theme: 'societe', level:  2, q: 'Quel océan borde la côte ouest de la France ?', a: 'L\'océan Atlantique.' },
  { theme: 'societe', level:  2, q: 'Que signifie le sigle ONU ?', a: 'Organisation des Nations unies.' },
  { theme: 'societe', level:  2, q: 'Quelle est la monnaie du Royaume-Uni ?', a: 'La livre sterling.' },
  { theme: 'societe', level:  2, q: 'Comment appelle-t-on le chef de l\'État en France ?', a: 'Le président de la République.' },
  { theme: 'societe', level:  2, q: 'Quel fleuve traverse Paris ?', a: 'La Seine.' },
  { theme: 'societe', level:  2, q: 'Combien de couleurs comporte le drapeau français ?', a: 'Trois.' },
  { theme: 'societe', level:  2, q: 'Quelle est la capitale de l\'Italie ?', a: 'Rome.' },
  { theme: 'societe', level:  3, q: 'Combien d\'étoiles figurent sur le drapeau européen ?', a: 'Douze.' },
  { theme: 'societe', level:  3, q: 'Que signifie le sigle PIB ?', a: 'Produit intérieur brut.' },
  { theme: 'societe', level:  3, q: 'Que signifie le sigle SNCF ?', a: 'Société nationale des chemins de fer français.' },
  { theme: 'societe', level:  3, q: 'Comment s\'appelle la chambre basse du Parlement français ?', a: 'L\'Assemblée nationale.' },
  { theme: 'societe', level:  3, q: 'Quelle figure allégorique représente la République française ?', a: 'Marianne.' },
  { theme: 'societe', level:  3, q: 'Quelle est la monnaie du Japon ?', a: 'Le yen.' },
  { theme: 'societe', level:  3, q: 'Que signifie le sigle OTAN ?', a: 'Organisation du traité de l\'Atlantique Nord.' },
  { theme: 'societe', level:  3, q: 'Que signifie l\'abréviation www sur Internet ?', a: 'World Wide Web.' },
  { theme: 'societe', level:  3, q: 'Que signifie le sigle TVA ?', a: 'Taxe sur la valeur ajoutée.' },
  { theme: 'societe', level:  3, q: 'Quelle est la langue officielle du Brésil ?', a: 'Le portugais.' },
  { theme: 'societe', level:  4, q: 'Combien d\'États membres compte l\'Union européenne ?', a: 'Vingt-sept.' },
  { theme: 'societe', level:  4, q: 'Que signifie le sigle FMI ?', a: 'Fonds monétaire international.' },
  { theme: 'societe', level:  4, q: 'Dans quelle ville se trouve le siège principal de l\'ONU ?', a: 'New York.' },
  { theme: 'societe', level:  4, q: 'Que signifie le sigle OMS ?', a: 'Organisation mondiale de la santé.' },
  { theme: 'societe', level:  4, q: 'Combien de régions métropolitaines compte la France depuis 2016 ?', a: 'Treize.' },
  { theme: 'societe', level:  4, q: 'Quelle est la capitale de l\'Allemagne ?', a: 'Berlin.' },
  { theme: 'societe', level:  4, q: 'Que signifie le sigle RGPD ?', a: 'Règlement général sur la protection des données.' },
  { theme: 'societe', level:  4, q: 'Quelle est la monnaie des États-Unis ?', a: 'Le dollar.' },
  { theme: 'societe', level:  4, q: 'Combien d\'années dure le mandat du président de la République française ?', a: 'Cinq ans.' },
  { theme: 'societe', level:  4, q: 'Dans quelle ville se réunit le Parlement européen en session plénière ?', a: 'Strasbourg.' },
  { theme: 'societe', level:  5, q: 'Combien de membres permanents siègent au Conseil de sécurité de l\'ONU ?', a: 'Cinq.' },
  { theme: 'societe', level:  5, q: 'Quel traité signé en 1992 a fondé l\'Union européenne ?', a: 'Le traité de Maastricht.' },
  { theme: 'societe', level:  5, q: 'Dans quelle ville se trouve le siège de la Commission européenne ?', a: 'Bruxelles.' },
  { theme: 'societe', level:  5, q: 'Quelle institution française contrôle la conformité des lois à la Constitution ?', a: 'Le Conseil constitutionnel.' },
  { theme: 'societe', level:  5, q: 'Que signifie le sigle PACS ?', a: 'Pacte civil de solidarité.' },
  { theme: 'societe', level:  5, q: 'Que signifie le sigle BCE ?', a: 'Banque centrale européenne.' },
  { theme: 'societe', level:  5, q: 'Que signifie le sigle UNESCO ?', a: 'Organisation des Nations unies pour l\'éducation, la science et la culture.' },
  { theme: 'societe', level:  5, q: 'Quelle est la capitale de l\'Australie ?', a: 'Canberra.' },
  { theme: 'societe', level:  5, q: 'Quelle chambre du Parlement français représente les collectivités territoriales ?', a: 'Le Sénat.' },
  { theme: 'societe', level:  5, q: 'En quelle année les pièces et billets en euros sont-ils entrés en circulation ?', a: 'En 2002.' },
  { theme: 'societe', level:  6, q: 'Dans quelle ville siège la Cour internationale de justice ?', a: 'La Haye.' },
  { theme: 'societe', level:  6, q: 'Comment appelle-t-on l\'espace européen de libre circulation sans contrôle aux frontières intérieures ?', a: 'L\'espace Schengen.' },
  { theme: 'societe', level:  6, q: 'Que signifie le sigle OCDE ?', a: 'Organisation de coopération et de développement économiques.' },
  { theme: 'societe', level:  6, q: 'En quelle année l\'ONU a-t-elle été créée ?', a: 'En 1945.' },
  { theme: 'societe', level:  6, q: 'Quelle est la monnaie de la Suisse ?', a: 'Le franc suisse.' },
  { theme: 'societe', level:  6, q: 'Combien de langues officielles compte l\'ONU ?', a: 'Six.' },
  { theme: 'societe', level:  6, q: 'Comment appelle-t-on la banque centrale des États-Unis ?', a: 'La Réserve fédérale (la Fed).' },
  { theme: 'societe', level:  6, q: 'Que signifie le sigle IVG ?', a: 'Interruption volontaire de grossesse.' },
  { theme: 'societe', level:  6, q: 'Dans quelle ville se trouve le siège du Conseil de l\'Europe ?', a: 'Strasbourg.' },
  { theme: 'societe', level:  6, q: 'Quel pays a quitté l\'Union européenne en 2020 lors du Brexit ?', a: 'Le Royaume-Uni.' },
  { theme: 'societe', level:  7, q: 'Quel traité signé en 1957 a créé la Communauté économique européenne ?', a: 'Le traité de Rome.' },
  { theme: 'societe', level:  7, q: 'Dans quelle ville se trouve le siège de l\'Organisation mondiale du commerce ?', a: 'Genève.' },
  { theme: 'societe', level:  7, q: 'Quel alinéa de l\'article 49 de la Constitution permet d\'adopter un texte sans vote en engageant la responsabilité du gouvernement ?', a: 'L\'article 49.3.' },
  { theme: 'societe', level:  7, q: 'Que signifie le sigle OPEP ?', a: 'Organisation des pays exportateurs de pétrole.' },
  { theme: 'societe', level:  7, q: 'Quelle est la capitale du Canada ?', a: 'Ottawa.' },
  { theme: 'societe', level:  7, q: 'Que signifie le sigle ONG ?', a: 'Organisation non gouvernementale.' },
  { theme: 'societe', level:  7, q: 'Que signifie le sigle FAO ?', a: 'Organisation des Nations unies pour l\'alimentation et l\'agriculture.' },
  { theme: 'societe', level:  7, q: 'Quelle institution de l\'UE réunit les chefs d\'État et de gouvernement pour fixer les grandes orientations ?', a: 'Le Conseil européen.' },
  { theme: 'societe', level:  7, q: 'Quelle est la monnaie de la Chine ?', a: 'Le yuan (renminbi).' },
  { theme: 'societe', level:  7, q: 'Combien de langues officielles compte l\'Union européenne ?', a: 'Vingt-quatre.' },
  { theme: 'societe', level:  8, q: 'Quel groupe réunit sept grandes puissances économiques lors d\'un sommet annuel ?', a: 'Le G7.' },
  { theme: 'societe', level:  8, q: 'Quel accord international adopté en 2015 vise à limiter le réchauffement climatique ?', a: 'L\'Accord de Paris.' },
  { theme: 'societe', level:  8, q: 'Dans quelle ville la Charte des Nations unies a-t-elle été signée en 1945 ?', a: 'San Francisco.' },
  { theme: 'societe', level:  8, q: 'Quel principe de l\'UE veut que les décisions soient prises au niveau le plus proche possible des citoyens ?', a: 'La subsidiarité.' },
  { theme: 'societe', level:  8, q: 'En quelle année le traité de Lisbonne a-t-il été signé ?', a: 'En 2007.' },
  { theme: 'societe', level:  8, q: 'Quelle est la capitale exécutive de l\'Afrique du Sud, siège du gouvernement ?', a: 'Pretoria.' },
  { theme: 'societe', level:  8, q: 'Comment appelle-t-on le groupe des grands pays émergents (Brésil, Russie, Inde, Chine, Afrique du Sud…) ?', a: 'Les BRICS.' },
  { theme: 'societe', level:  8, q: 'Quel indice, publié par le PNUD, mesure le niveau de développement humain d\'un pays ?', a: 'L\'IDH (indice de développement humain).' },
  { theme: 'societe', level:  8, q: 'Que désigne le sigle CEDH lorsqu\'il nomme la juridiction siégeant à Strasbourg ?', a: 'La Cour européenne des droits de l\'homme.' },
  { theme: 'societe', level:  8, q: 'Quelle est la capitale du Kazakhstan ?', a: 'Astana.' },
  { theme: 'societe', level:  9, q: 'Quel économiste écossais est l\'auteur de « La Richesse des nations » (1776) ?', a: 'Adam Smith.' },
  { theme: 'societe', level:  9, q: 'Quels traités de 1648 sont considérés comme fondateurs des relations internationales modernes ?', a: 'Les traités de Westphalie.' },
  { theme: 'societe', level:  9, q: 'Quel économiste britannique a théorisé l\'intervention de l\'État dans sa « Théorie générale » de 1936 ?', a: 'John Maynard Keynes.' },
  { theme: 'societe', level:  9, q: 'Que signifie le sigle AIEA ?', a: 'Agence internationale de l\'énergie atomique.' },
  { theme: 'societe', level:  9, q: 'Dans quelle ville se trouve le siège de l\'AIEA ?', a: 'Vienne.' },
  { theme: 'societe', level:  9, q: 'Que signifie le sigle AELE ?', a: 'Association européenne de libre-échange.' },
  { theme: 'societe', level:  9, q: 'Quel économiste a formulé la théorie des avantages comparatifs ?', a: 'David Ricardo.' },
  { theme: 'societe', level:  9, q: 'Quelle conférence de 1944 a instauré le système monétaire international de l\'après-guerre ?', a: 'Bretton Woods.' },
  { theme: 'societe', level:  9, q: 'Quel traité de 1968 vise à empêcher la diffusion des armes nucléaires ?', a: 'Le TNP (Traité sur la non-prolifération).' },
  { theme: 'societe', level:  9, q: 'Quelle conférence de février 1945 a réuni Churchill, Roosevelt et Staline ?', a: 'La conférence de Yalta.' },
  { theme: 'societe', level: 10, q: 'Quel article du Traité sur l\'Union européenne organise le retrait volontaire d\'un État membre ?', a: 'L\'article 50.' },
  { theme: 'societe', level: 10, q: 'Quel article du Traité sur l\'Union européenne prévoit la clause de défense mutuelle entre États membres ?', a: 'L\'article 42.7.' },
  { theme: 'societe', level: 10, q: 'Dans quelle ville suisse le Comité international de la Croix-Rouge a-t-il été fondé ?', a: 'Genève.' },
  { theme: 'societe', level: 10, q: 'Quel diplomate suédois fut le deuxième secrétaire général de l\'ONU ?', a: 'Dag Hammarskjöld.' },
  { theme: 'societe', level: 10, q: 'Quelle est la capitale administrative du Sri Lanka ?', a: 'Sri Jayawardenepura Kotte.' },
  { theme: 'societe', level: 10, q: 'Quel juriste autrichien est l\'auteur de la théorie de la « pyramide des normes » ?', a: 'Hans Kelsen.' },
  { theme: 'societe', level: 10, q: 'Quel économiste italien a donné son nom à un critère d\'optimum en économie du bien-être ?', a: 'Vilfredo Pareto.' },
  { theme: 'societe', level: 10, q: 'Quelle organisation, siégeant à Bâle, coordonne la coopération entre banques centrales ?', a: 'La Banque des règlements internationaux (BRI).' },
  { theme: 'societe', level: 10, q: 'Quel accord de 1985 est à l\'origine de la suppression des contrôles aux frontières intérieures européennes ?', a: 'Les accords de Schengen.' },
  { theme: 'societe', level: 10, q: 'Quel penseur français est l\'auteur de « De l\'esprit des lois » et de la séparation des pouvoirs ?', a: 'Montesquieu.' },

];
